In [1]:
import numpy
n = numpy.arange(27)

In [3]:
type(n)

numpy.ndarray

In [6]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
m= numpy.asarray([[123,12,123,12,33],[],[]])

In [10]:
print(m)

[[123, 12, 123, 12, 33] [] []]


In [1]:
type(m)

NameError: name 'm' is not defined

In [2]:
import cv2

In [3]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
im_g=cv2.imread("smallgray.png",1)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [5]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [9]:
im_g=cv2.imread("smallgray.png",0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [11]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [13]:
im_g.shape

(3, 5)

In [14]:
im_g[2,4]

182